version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ledgerlift
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  minio:
    image: minio/minio:RELEASE.2024-05-28T17-19-04Z
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

  minio-setup:
    image: minio/mc:RELEASE.2024-05-24T17-11-14Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb -p local/ledger-lift || true;
      /usr/bin/mc anonymous set download local/ledger-lift;
      exit 0;
      "

  localstack:
    image: localstack/localstack:2.3
    environment:
      - SERVICES=sqs
      - DEBUG=0
    ports:
      - "4566:4566"

  api:
    build:
      context: ./apps/api
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/ledgerlift
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: ledger-lift
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_REGION: us-east-1
      CORS_ORIGINS: http://localhost:3000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - minio
      - minio-setup
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  pg:
  minio:
