[[redirects]]
  from = "/api/jobs/:jobId/audit"
  to = "/.netlify/functions/get-audit-trail?jobId=:jobId"
  status = 200

[[redirects]]
  from = "/api/jobs/:jobId/delete"
  to = "/.netlify/functions/delete-job"
  status = 200

[[redirects]]
  from = "/api/jobs/:jobId/schedules"
  to = "/.netlify/functions/get-job-schedules?jobId=:jobId"
  status = 200

[[redirects]]
  from = "/api/jobs/:jobId/export"
  to = "/.netlify/functions/export-job?jobId=:jobId"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg"]
